const TABLE_MANAGER = 'MANAGERS'
const COLUM_ID_MANAGER = 'ID'
const COLUM_USER_NAME_MANAGER = 'USER_NAME'
const COLUM_EMAIL_MANAGER = 'EMAIL'
const COLUM_PASSWORD_MANAGER = 'PASSWORD'
const COLUM_PHONE_NUMBER_MANAGER = 'PHONE_NUMBER'
const COLUM_IMAGE_MANAGER = 'IMAGE'
const COLUM_ROLE_MANGER = 'ROLE'
const COLUM_IS_ACTIVE_MANAGER = 'IS_ACTIVE'
const COLUM_IS_CONFIRM_MANAGER = 'IS_CONFIRM'
const COLUM_IS_VERIFY_MANAGER = 'IS_VERIFY'
const COLUM_CREATED_AT_MANAGER = 'CREATED_AT'
const COLUM_UDATED_AT_MANAGER = 'UPDATED_AT'

const TableName = {
    TABLE_MANAGER, COLUM_ID_MANAGER, COLUM_USER_NAME_MANAGER, COLUM_EMAIL_MANAGER, COLUM_PASSWORD_MANAGER,
    COLUM_PHONE_NUMBER_MANAGER, COLUM_IMAGE_MANAGER, COLUM_IMAGE_MANAGER, COLUM_ROLE_MANGER, COLUM_IS_ACTIVE_MANAGER,
    COLUM_IS_CONFIRM_MANAGER, COLUM_IS_VERIFY_MANAGER, COLUM_CREATED_AT_MANAGER, COLUM_UDATED_AT_MANAGER,
}

export default TableName