const TABLE_MANAGER = 'MANAGERS'
const COLUM_ID_MANAGER = 'ID'
const COLUM_USER_NAME_MANAGER = 'USER_NAME'
const COLUM_EMAIL_MANAGER = 'EMAIL'
const COLUM_PASSWORD_MANAGER = 'PASSWORD'
const COLUM_PHONE_NUMBER_MANAGER = 'PHONE_NUMBER'
const COLUM_IMAGE_MANAGER = 'IMAGE'
const COLUM_ROLE_MANGER = 'ROLE'
const COLUM_IS_ACTIVE_MANAGER = 'IS_ACTIVE'
const COLUM_IS_CONFIRM_MANAGER = 'IS_CONFIRM'
const COLUM_IS_VERIFY_MANAGER = 'IS_VERIFY'
const COLUM_CREATED_AT_MANAGER = 'CREATED_AT'
const COLUM_UDATED_AT_MANAGER = 'UPDATED_AT'

const TABLE_CATEGORY = 'CATEGORIES'
const COLUM_ID_CATEGORY = 'ID'
const COLUM_ID_MANAGER_CATEGORY = 'CREATED_BY_MANAGER'
const COLUM_CATEGORY_NAME = 'CATEGORY_NAME'
const COLUM_CREATED_AT_CATEGORY = 'CREATED_AT'
const COLUM_UPDATED_AT_CATEGORY = 'UPDATED_AT'

const TABLE_COMPANY = 'COMPANIES'
const COLUM_ID_COMPANY = 'ID'
const COLUM_ID_MANAGER_COMPANY = 'CREATED_BY_MANAGER'
const COLUM_COMPANY_NAME = 'COMPANY_NAME'
const COLUM_IMAGE_COMPANY = 'IMAGE'
const COLUM_COUNTRIES_COMPANY = 'COUNTRIES'
const COLUM_CREATED_AT_COMPANY = 'CREATED_AT'
const COLUM_UPDATED_AT_COMPANY = 'UPDATED_AT'

const TableName = {
    TABLE_MANAGER, COLUM_ID_MANAGER, COLUM_USER_NAME_MANAGER, COLUM_EMAIL_MANAGER, COLUM_PASSWORD_MANAGER,
    COLUM_PHONE_NUMBER_MANAGER, COLUM_IMAGE_MANAGER, COLUM_IMAGE_MANAGER, COLUM_ROLE_MANGER, COLUM_IS_ACTIVE_MANAGER,
    COLUM_IS_CONFIRM_MANAGER, COLUM_IS_VERIFY_MANAGER, COLUM_CREATED_AT_MANAGER, COLUM_UDATED_AT_MANAGER,

    TABLE_CATEGORY, COLUM_ID_CATEGORY, COLUM_ID_MANAGER_CATEGORY, COLUM_CATEGORY_NAME, 
    COLUM_CREATED_AT_CATEGORY, COLUM_UPDATED_AT_CATEGORY,

    TABLE_COMPANY, COLUM_ID_MANAGER_COMPANY, COLUM_COMPANY_NAME, COLUM_IMAGE_COMPANY,
    COLUM_CREATED_AT_COMPANY, COLUM_UPDATED_AT_COMPANY, COLUM_ID_COMPANY, COLUM_COUNTRIES_COMPANY,

    
}

export default TableName